//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Tracker_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStarNumbers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStarNumbers()
        {
            this.tblUsersComments = new HashSet<tblUsersComments>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StarNumbers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersComments> tblUsersComments { get; set; }
    }
}
