//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food_Tracker_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsersComments
    {
        public int Id { get; set; }
        public int RestaurantId { get; set; }
        public string Comment { get; set; }
        public int StarNumbersId { get; set; }
        public int UserId { get; set; }
    
        public virtual tblRestaurant tblRestaurant { get; set; }
        public virtual tblStarNumbers tblStarNumbers { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
